/*
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.rosi.crom.validation.mapping.FeatureMappingRuntimeModule
import org.rosi.crom.validation.mapping.FeatureMappingStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FeatureMappingIdeSetup extends FeatureMappingStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FeatureMappingRuntimeModule, new FeatureMappingIdeModule))
	}
	
}
