/*
 * generated by Xtext 2.14.0
 */
package org.rosi.crom.validation.mapping.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOclMappingScopeProvider extends DelegatingScopeProvider {
}
