/*
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OclMappingStandaloneSetup extends OclMappingStandaloneSetupGenerated {

	def static void doSetup() {
		new OclMappingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
