/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.ui.contentassist;

import org.rosi.crom.validation.mapping.ui.contentassist.AbstractOclMappingProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OclMappingProposalProvider extends AbstractOclMappingProposalProvider {
}
