/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.rosi.crom.validation.mapping.ui.AbstractFeatureMappingUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FeatureMappingUiModule extends AbstractFeatureMappingUiModule {
  public FeatureMappingUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
