/*
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.rosi.crom.validation.mapping.featureMapping.Feature;
import org.rosi.crom.validation.mapping.featureMapping.FeatureMappingPackage;
import org.rosi.crom.validation.mapping.featureMapping.Invariant;
import org.rosi.crom.validation.mapping.featureMapping.Model;
import org.rosi.crom.validation.mapping.featureMapping.Universal;
import org.rosi.crom.validation.mapping.services.FeatureMappingGrammarAccess;

@SuppressWarnings("all")
public class FeatureMappingSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private FeatureMappingGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == FeatureMappingPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case FeatureMappingPackage.FEATURE:
				sequence_Feature(context, (Feature) semanticObject); 
				return; 
			case FeatureMappingPackage.INVARIANT:
				sequence_Invariant(context, (Invariant) semanticObject); 
				return; 
			case FeatureMappingPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case FeatureMappingPackage.UNIVERSAL:
				sequence_Universal(context, (Universal) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Feature returns Feature
	 *
	 * Constraint:
	 *     (name=ID elements+=Invariant+)
	 */
	protected void sequence_Feature(ISerializationContext context, Feature semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Invariant returns Invariant
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Invariant(ISerializationContext context, Invariant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, FeatureMappingPackage.Literals.INVARIANT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, FeatureMappingPackage.Literals.INVARIANT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInvariantAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (elements+=Universal | elements+=Feature)+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Universal returns Universal
	 *
	 * Constraint:
	 *     elements+=Invariant+
	 */
	protected void sequence_Universal(ISerializationContext context, Universal semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
