/*
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.rosi.crom.validation.mapping.ui.internal.MappingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OclMappingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MappingActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MappingActivator activator = MappingActivator.getInstance();
		return activator != null ? activator.getInjector(MappingActivator.ORG_ROSI_CROM_VALIDATION_MAPPING_OCLMAPPING) : null;
	}

}
