/*
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.rosi.crom.validation.mapping.parser.antlr.internal.InternalFeatureMappingParser;
import org.rosi.crom.validation.mapping.services.FeatureMappingGrammarAccess;

public class FeatureMappingParser extends AbstractAntlrParser {

	@Inject
	private FeatureMappingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFeatureMappingParser createParser(XtextTokenStream stream) {
		return new InternalFeatureMappingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public FeatureMappingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FeatureMappingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
