/*
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.rosi.crom.validation.mapping.parser.antlr.internal.InternalOclMappingParser;
import org.rosi.crom.validation.mapping.services.OclMappingGrammarAccess;

public class OclMappingParser extends AbstractAntlrParser {

	@Inject
	private OclMappingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOclMappingParser createParser(XtextTokenStream stream) {
		return new InternalOclMappingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public OclMappingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OclMappingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
