/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping;

import org.rosi.crom.validation.mapping.AbstractFeatureMappingRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FeatureMappingRuntimeModule extends AbstractFeatureMappingRuntimeModule {
}
