/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping;

import org.rosi.crom.validation.mapping.FeatureMappingStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FeatureMappingStandaloneSetup extends FeatureMappingStandaloneSetupGenerated {
  public static void doSetup() {
    new FeatureMappingStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
