/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.validation;

import org.rosi.crom.validation.mapping.validation.AbstractFeatureMappingValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FeatureMappingValidator extends AbstractFeatureMappingValidator {
}
