/**
 * generated by Xtext 2.14.0
 */
package org.rosi.crom.validation.mapping.oclMapping;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.rosi.crom.validation.mapping.oclMapping.Expression#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.rosi.crom.validation.mapping.oclMapping.OclMappingPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Feature
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.rosi.crom.validation.mapping.oclMapping.Invariant}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.rosi.crom.validation.mapping.oclMapping.OclMappingPackage#getExpression_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Invariant> getElements();

} // Expression
