/**
 * generated by Xtext 2.14.0
 */
package org.rosi.crom.validation.mapping.oclMapping;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.rosi.crom.validation.mapping.oclMapping.OclMappingPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
} // Feature
