/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.featureMapping;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.rosi.crom.validation.mapping.featureMapping.FeatureMappingFactory
 * @model kind="package"
 * @generated
 */
public interface FeatureMappingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "featureMapping";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.rosi.org/crom/validation/mapping/FeatureMapping";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "featureMapping";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FeatureMappingPackage eINSTANCE = org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl.init();

  /**
   * The meta object id for the '{@link org.rosi.crom.validation.mapping.featureMapping.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.rosi.crom.validation.mapping.featureMapping.impl.ModelImpl
   * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.rosi.crom.validation.mapping.featureMapping.impl.UniversalImpl <em>Universal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.rosi.crom.validation.mapping.featureMapping.impl.UniversalImpl
   * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl#getUniversal()
   * @generated
   */
  int UNIVERSAL = 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIVERSAL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Universal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIVERSAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.rosi.crom.validation.mapping.featureMapping.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureImpl
   * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.rosi.crom.validation.mapping.featureMapping.impl.InvariantImpl <em>Invariant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.rosi.crom.validation.mapping.featureMapping.impl.InvariantImpl
   * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl#getInvariant()
   * @generated
   */
  int INVARIANT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVARIANT__NAME = 0;

  /**
   * The number of structural features of the '<em>Invariant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVARIANT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.rosi.crom.validation.mapping.featureMapping.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.rosi.crom.validation.mapping.featureMapping.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.rosi.crom.validation.mapping.featureMapping.Universal <em>Universal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Universal</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Universal
   * @generated
   */
  EClass getUniversal();

  /**
   * Returns the meta object for the containment reference list '{@link org.rosi.crom.validation.mapping.featureMapping.Universal#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Universal#getElements()
   * @see #getUniversal()
   * @generated
   */
  EReference getUniversal_Elements();

  /**
   * Returns the meta object for class '{@link org.rosi.crom.validation.mapping.featureMapping.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link org.rosi.crom.validation.mapping.featureMapping.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.rosi.crom.validation.mapping.featureMapping.Feature#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Feature#getElements()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Elements();

  /**
   * Returns the meta object for class '{@link org.rosi.crom.validation.mapping.featureMapping.Invariant <em>Invariant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Invariant</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Invariant
   * @generated
   */
  EClass getInvariant();

  /**
   * Returns the meta object for the attribute '{@link org.rosi.crom.validation.mapping.featureMapping.Invariant#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.rosi.crom.validation.mapping.featureMapping.Invariant#getName()
   * @see #getInvariant()
   * @generated
   */
  EAttribute getInvariant_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FeatureMappingFactory getFeatureMappingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.rosi.crom.validation.mapping.featureMapping.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.rosi.crom.validation.mapping.featureMapping.impl.ModelImpl
     * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.rosi.crom.validation.mapping.featureMapping.impl.UniversalImpl <em>Universal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.rosi.crom.validation.mapping.featureMapping.impl.UniversalImpl
     * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl#getUniversal()
     * @generated
     */
    EClass UNIVERSAL = eINSTANCE.getUniversal();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNIVERSAL__ELEMENTS = eINSTANCE.getUniversal_Elements();

    /**
     * The meta object literal for the '{@link org.rosi.crom.validation.mapping.featureMapping.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureImpl
     * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__ELEMENTS = eINSTANCE.getFeature_Elements();

    /**
     * The meta object literal for the '{@link org.rosi.crom.validation.mapping.featureMapping.impl.InvariantImpl <em>Invariant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.rosi.crom.validation.mapping.featureMapping.impl.InvariantImpl
     * @see org.rosi.crom.validation.mapping.featureMapping.impl.FeatureMappingPackageImpl#getInvariant()
     * @generated
     */
    EClass INVARIANT = eINSTANCE.getInvariant();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INVARIANT__NAME = eINSTANCE.getInvariant_Name();

  }

} //FeatureMappingPackage
