/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.ide;

import org.rosi.crom.validation.mapping.ide.AbstractFeatureMappingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FeatureMappingIdeModule extends AbstractFeatureMappingIdeModule {
}
