/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.rosi.crom.validation.mapping.FeatureMappingRuntimeModule;
import org.rosi.crom.validation.mapping.FeatureMappingStandaloneSetup;
import org.rosi.crom.validation.mapping.ide.FeatureMappingIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class FeatureMappingIdeSetup extends FeatureMappingStandaloneSetup {
  @Override
  public Injector createInjector() {
    FeatureMappingRuntimeModule _featureMappingRuntimeModule = new FeatureMappingRuntimeModule();
    FeatureMappingIdeModule _featureMappingIdeModule = new FeatureMappingIdeModule();
    return Guice.createInjector(Modules2.mixin(_featureMappingRuntimeModule, _featureMappingIdeModule));
  }
}
