/**
 * generated by Xtext 2.15.0
 */
package org.rosi.crom.validation.mapping.ide;

import org.rosi.crom.validation.mapping.ide.AbstractOclMappingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class OclMappingIdeModule extends AbstractOclMappingIdeModule {
}
